<?php 

    //##############################################################################################\\
    //                                                                                              \\
    //  DO NOT EDIT THIS FILE MANUALLY. IT IS AUTOMATICALLY GENERATED BY THE PLUGIN SETTINGS PAGE.  \\
    //                                                                                              \\

        // Device widths resolutions. 

        $resolutions = array( 1920, 1600, 1440, 1280, 1024, 640, 480 ); 

        // Whether to take the landscape width into account or not. 

        $landscape = FALSE; 

        // Whether to show higher resolution images to HiDPI screens or not. 

        $hidpi = FALSE; 

        // The directory of the images cache. 

        $cache_dir = "cache/adaptive-images"; 

        // JPEG quality of resized images. 

        $jpg_quality = 75; 

        // Sharpen resized images. 

        $sharpen = FALSE; 

        // Check for new versions of cached images. 

        $watch_cache = TRUE; 

        // Browser cache duration for images. 

        $browser_cache = 60 * 60 * 24 * 180; 

    //                                                                                              \\
    //  DO NOT EDIT THIS FILE MANUALLY. IT IS AUTOMATICALLY GENERATED BY THE PLUGIN SETTINGS PAGE.  \\
    //                                                                                              \\
    //==============================================================================================\\

?>